### ISSUE TITLE
Crash on server, "Unable to get public no-arg constructor"

### ISSUE THREAD

**Issue by mosharky** [Dariensg/Hellions-Sniffer-Plus#1] opened 2023-06-13 17:30 UTC
[Crash report](https://gist.github.com/mosharky/017d5b16197385f486002f6bf206e49c)

Let me know what kind of information I could provide

**Comment by Dariensg** [comment] 2023-06-13 20:13
There are other errors there that seem to be crashing the game first and I have a feeling they're the real issue. Entity Model Features is trying to load client-sided code on the server. You should report that to them. If you remove Entity Model Features, does it work as intended or still crash?

**Comment by mosharky** [comment] 2023-06-13 20:17
The Sniffer+ error was the first one I saw, so I reported that. I realized after that I had a few client-sided mods that can't run on servers as well, and after removing those and re-adding this mod, I still crashed because of this mod.

**Comment by Dariensg** [comment] 2023-06-13 21:51
Could I please have the crash report from the time without the client-sided mods?

**Comment by mosharky** [comment] 2023-06-13 23:53
Tested with exclusively this mod:
[server log](https://gist.github.com/mosharky/7ed0d2d56508f0129c52402198e001ee)
[server crash report](https://gist.github.com/mosharky/82fd26eb77c5404f2b098cc915744400)

sorry for not providing these earlier, something came up

**Comment by Dariensg** [comment] 2023-06-14 01:24
Ah interesting! Yup, that's definitely my bad. I'll take a look at it in the next couple days. Wednesday and Thursday are typically my days off, but I should have some time Thursday I believe!

**Comment by mosharky** [comment] 2023-06-14 12:02
No worries! No need to rush :)

**Comment by Dariensg** [comment] 2023-06-16 17:51
This bug should be fixed as of v0.2.0! If it still crashes, let me know, but I tested a dedicated server on both Forge and Fabric with no issues!

**Closed as completed** 2023-06-16 17:51 UTC
Labels: bug
