### ISSUE TITLE
Game Crashing on Startup Latest Forge 1.201

### ISSUE THREAD

**Issue by realBritakee** [Dariensg/Hellions-Sniffer-Plus#4] opened 2023-07-08 10:08 UTC
https://pastebin.com/wjmYnDKB

**Comment by Dariensg** [comment] 2023-07-08 13:41
Hi, please submit a full log rather than just a crash report. This crash is not actually caused by Sniffer+, but the real reason isn't shown in the crash report. Thank you!

**Comment by drakray** [comment] 2023-07-12 04:50
I had the same crash, but looking at the Debug.log I found that some other mods crashed, like InventoryProfileNext and JEI(near the end of file)
Updated those and it's working now, really weird that Forge accuse another mod though :/

**Comment by Dariensg** [comment] 2023-07-12 04:59
Yeah, I think it's because those issues are caught by Forge and will display an error after startup rather than outright crashing, but the Registries freeze which end up crashing my mod. So mine crashes immediately before Forge will display their error for the true culprits. I'm gonna close this issue since the OP isn't responding.

**Closed as completed by Dariensg** 2023-07-12 04:59 UTC
