### ISSUE TITLE
[1.20.1] Sniffer+ and Apotheosis causes automatic step up for the player

### ISSUE THREAD

**Issue by BugmanBugman** [Dariensg/Hellions-Sniffer-Plus#10] opened 2023-08-14 22:43 UTC

**Comment by embeddedt** [comment] 2023-08-14 23:01
Looks like the `EntityMixin` here is an earlier version of https://github.com/MinecraftForge/MinecraftForge/pull/9583. As the issue is now fixed in Forge the mixin can probably be safely removed.

**Comment by Dariensg** [comment] 2023-08-14 23:11
Yes, it is. I discovered the issue and reported it to Forge but was told I'd have to wait for it to get fixed and just should implement the fix myself in the meantime. I'll remove that in the next version!

**Comment by Peach774** [comment] 2023-11-21 20:54
Hey, has there been any update on this? The problem is driving me crazy

**Comment by katubug** [comment] 2024-02-22 20:03
I too am having this issue and would like it resolved if possible.

**Closed as completed** 2024-04-14 19:13 UTC
Labels: bug
